/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicImport } from './routes/_public'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthImport } from './routes/_auth'
import { Route as PublicAboutIndexImport } from './routes/_public/about/index'
import { Route as AuthenticatedDashboardIndexImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedModulesIndexImport } from './routes/_authenticated/_modules/index'
import { Route as AuthRegisterIndexImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexImport } from './routes/_auth/login/index'
import { Route as AuthenticatedModulesAccountingImport } from './routes/_authenticated/_modules/accounting'
import { Route as AuthenticatedModulesAccountingGeneralLedgerIndexImport } from './routes/_authenticated/_modules/accounting/general-ledger/index'

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const PublicAboutIndexRoute = PublicAboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => PublicRoute,
} as any)

const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedModulesIndexRoute = AuthenticatedModulesIndexImport.update({
  id: '/_modules/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthRegisterIndexRoute = AuthRegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthenticatedModulesAccountingRoute =
  AuthenticatedModulesAccountingImport.update({
    id: '/_modules/accounting',
    path: '/accounting',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedModulesAccountingGeneralLedgerIndexRoute =
  AuthenticatedModulesAccountingGeneralLedgerIndexImport.update({
    id: '/general-ledger/',
    path: '/general-ledger/',
    getParentRoute: () => AuthenticatedModulesAccountingRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_modules/accounting': {
      id: '/_authenticated/_modules/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthenticatedModulesAccountingImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterIndexImport
      parentRoute: typeof AuthImport
    }
    '/_authenticated/_modules/': {
      id: '/_authenticated/_modules/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedModulesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_public/about/': {
      id: '/_public/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutIndexImport
      parentRoute: typeof PublicImport
    }
    '/_authenticated/_modules/accounting/general-ledger/': {
      id: '/_authenticated/_modules/accounting/general-ledger/'
      path: '/general-ledger'
      fullPath: '/accounting/general-ledger'
      preLoaderRoute: typeof AuthenticatedModulesAccountingGeneralLedgerIndexImport
      parentRoute: typeof AuthenticatedModulesAccountingImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedModulesAccountingRouteChildren {
  AuthenticatedModulesAccountingGeneralLedgerIndexRoute: typeof AuthenticatedModulesAccountingGeneralLedgerIndexRoute
}

const AuthenticatedModulesAccountingRouteChildren: AuthenticatedModulesAccountingRouteChildren =
  {
    AuthenticatedModulesAccountingGeneralLedgerIndexRoute:
      AuthenticatedModulesAccountingGeneralLedgerIndexRoute,
  }

const AuthenticatedModulesAccountingRouteWithChildren =
  AuthenticatedModulesAccountingRoute._addFileChildren(
    AuthenticatedModulesAccountingRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedModulesAccountingRoute: typeof AuthenticatedModulesAccountingRouteWithChildren
  AuthenticatedModulesIndexRoute: typeof AuthenticatedModulesIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedModulesAccountingRoute:
    AuthenticatedModulesAccountingRouteWithChildren,
  AuthenticatedModulesIndexRoute: AuthenticatedModulesIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutIndexRoute: typeof PublicAboutIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutIndexRoute: PublicAboutIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PublicRouteWithChildren
  '/accounting': typeof AuthenticatedModulesAccountingRouteWithChildren
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/': typeof AuthenticatedModulesIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/about': typeof PublicAboutIndexRoute
  '/accounting/general-ledger': typeof AuthenticatedModulesAccountingGeneralLedgerIndexRoute
}

export interface FileRoutesByTo {
  '': typeof PublicRouteWithChildren
  '/accounting': typeof AuthenticatedModulesAccountingRouteWithChildren
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/': typeof AuthenticatedModulesIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/about': typeof PublicAboutIndexRoute
  '/accounting/general-ledger': typeof AuthenticatedModulesAccountingGeneralLedgerIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/_modules/accounting': typeof AuthenticatedModulesAccountingRouteWithChildren
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_authenticated/_modules/': typeof AuthenticatedModulesIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_public/about/': typeof PublicAboutIndexRoute
  '/_authenticated/_modules/accounting/general-ledger/': typeof AuthenticatedModulesAccountingGeneralLedgerIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/accounting'
    | '/login'
    | '/register'
    | '/'
    | '/dashboard'
    | '/about'
    | '/accounting/general-ledger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/accounting'
    | '/login'
    | '/register'
    | '/'
    | '/dashboard'
    | '/about'
    | '/accounting/general-ledger'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/_modules/accounting'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_authenticated/_modules/'
    | '/_authenticated/dashboard/'
    | '/_public/about/'
    | '/_authenticated/_modules/accounting/general-ledger/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_authenticated",
        "/_public"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login/",
        "/_auth/register/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_modules/accounting",
        "/_authenticated/_modules/",
        "/_authenticated/dashboard/"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/about/"
      ]
    },
    "/_authenticated/_modules/accounting": {
      "filePath": "_authenticated/_modules/accounting.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_modules/accounting/general-ledger/"
      ]
    },
    "/_auth/login/": {
      "filePath": "_auth/login/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/register/": {
      "filePath": "_auth/register/index.tsx",
      "parent": "/_auth"
    },
    "/_authenticated/_modules/": {
      "filePath": "_authenticated/_modules/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/": {
      "filePath": "_authenticated/dashboard/index.tsx",
      "parent": "/_authenticated"
    },
    "/_public/about/": {
      "filePath": "_public/about/index.tsx",
      "parent": "/_public"
    },
    "/_authenticated/_modules/accounting/general-ledger/": {
      "filePath": "_authenticated/_modules/accounting/general-ledger/index.tsx",
      "parent": "/_authenticated/_modules/accounting"
    }
  }
}
ROUTE_MANIFEST_END */
